//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsTrackingSite.Resource
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public lang()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsTrackingSite.Resource.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Açıklama
        {
            get
            {
                return ResourceManager.GetString("Açıklama", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad
        {
            get
            {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toplam Yönetici Sayısı.
        /// </summary>
        public static string AdminCount
        {
            get
            {
                return ResourceManager.GetString("AdminCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aktör İşlemleri.
        /// </summary>
        //public static string Aktörİşlemleri
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("Aktörİşlemleri", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to ANA SAYFA.
        /// </summary>
        public static string AnaSayfa
        {
            get
            {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ARAMA.
        /// </summary>
        public static string Arama
        {
            get
            {
                return ResourceManager.GetString("Arama", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ARŞİVİ.
        /// </summary>
        public static string Sitesi
        {
            get
            {
                return ResourceManager.GetString("Sitesi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bütçe.
        /// </summary>
        //public static string Bütçe
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("Bütçe", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to ÇIKACAK FİLMLER.
        /// </summary>
        //public static string ÇıkacakHaberler
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("ÇıkacakHaberler", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to ÇIKIŞ.
        /// </summary>
        public static string Çıkış
        {
            get
            {
                return ResourceManager.GetString("Çıkış", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        public static string Dashboard
        {
            get
            {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detayları Göster.
        /// </summary>
        public static string DetayGöster
        {
            get
            {
                return ResourceManager.GetString("DetayGöster", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string DogumTarih
        {
            get
            {
                return ResourceManager.GetString("DogumTarih", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Düzenle
        {
            get
            {
                return ResourceManager.GetString("Düzenle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMail
        {
            get
            {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FİLM.
        /// </summary>
        public static string Haber
        {
            get
            {
                return ResourceManager.GetString("Haber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Adı.
        /// </summary>
        public static string HaberAd
        {
            get
            {
                return ResourceManager.GetString("HaberAd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FİLM ARŞİV ADMİN.
        /// </summary>
        public static string HaberSitesiAdmin
        {
            get
            {
                return ResourceManager.GetString("HaberSitesiAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FİLM ARŞİVİ.
        /// </summary>
        public static string HaberSitesi
        {
            get
            {
                return ResourceManager.GetString("HaberSitesi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FİLM DETAY.
        /// </summary>
        public static string HaberDetay
        {
            get
            {
                return ResourceManager.GetString("HaberDetay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        public static string HaberEkle
        {
            get
            {
                return ResourceManager.GetString("HaberEkle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Fotoğrafı.
        /// </summary>
        public static string HaberFoto
        {
            get
            {
                return ResourceManager.GetString("HaberFoto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber İşlemleri.
        /// </summary>
        public static string Haberİşlemleri
        {
            get
            {
                return ResourceManager.GetString("Haberİşlemleri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Linki.
        /// </summary>
        public static string HaberLinki
        {
            get
            {
                return ResourceManager.GetString("HaberLinki", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Sil.
        /// </summary>
        public static string HaberSil
        {
            get
            {
                return ResourceManager.GetString("HaberSil", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Haber Türleri İşlemleri.
        /// </summary>
        public static string HaberTürleriİşlemleri
        {
            get
            {
                return ResourceManager.GetString("HaberTürleriİşlemleri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eklenmiş Tür Sayısı.
        /// </summary>
        public static string GenreCount
        {
            get
            {
                return ResourceManager.GetString("GenreCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ.
        /// </summary>
        public static string GİRİŞ
        {
            get
            {
                return ResourceManager.GetString("GİRİŞ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GÖNDER.
        /// </summary>
        public static string Gönder
        {
            get
            {
                return ResourceManager.GetString("Gönder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HAFTANIN FİLMLERİ.
        /// </summary>
        public static string HaftanınHaberleri
        {
            get
            {
                return ResourceManager.GetString("HaftanınHaberleri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to İçerik Yönetimi.
        /// </summary>
        public static string İçerikYönetim
        {
            get
            {
                return ResourceManager.GetString("İçerikYönetim", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string İletişim
        {
            get
            {
                return ResourceManager.GetString("İletişim", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KATEGORİLER.
        /// </summary>
        public static string Kategoriler
        {
            get
            {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KAYDET.
        /// </summary>
        public static string Kaydet
        {
            get
            {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KAYIT OL.
        /// </summary>
        public static string KayıtOl
        {
            get
            {
                return ResourceManager.GetString("KayıtOl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        public static string KayıtTarih
        {
            get
            {
                return ResourceManager.GetString("KayıtTarih", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı İşlemleri.
        /// </summary>
        public static string Kullanıcıİşlemler
        {
            get
            {
                return ResourceManager.GetString("Kullanıcıİşlemler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Mesaj
        {
            get
            {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eklenmiş Haber Sayısı.
        /// </summary>
        public static string NewsCount
        {
            get
            {
                return ResourceManager.GetString("NewsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neredeyiz ?.
        /// </summary>
        public static string Neredeyiz
        {
            get
            {
                return ResourceManager.GetString("Neredeyiz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Oluştur
        {
            get
            {
                return ResourceManager.GetString("Oluştur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ÖNERİLEN FİLMLER.
        /// </summary>
        public static string ÖnerilenHaberler
        {
            get
            {
                return ResourceManager.GetString("ÖnerilenHaberler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oyuncular.
        /// </summary>
        //public static string Oyuncular
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("Oyuncular", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to Profil Fotoğrafı.
        /// </summary>
        public static string ProfilFoto
        {
            get
            {
                return ResourceManager.GetString("ProfilFoto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PUAN.
        /// </summary>
        public static string Puan
        {
            get
            {
                return ResourceManager.GetString("Puan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Şifre
        {
            get
            {
                return ResourceManager.GetString("Şifre", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SİNEMALARDA BU HAFTA.
        /// </summary>
        //public static string SinemalardaBuHafta
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("SinemalardaBuHafta", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to SİTEYE GİT.
        /// </summary>
        public static string SiteyeGit
        {
            get
            {
                return ResourceManager.GetString("SiteyeGit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string SoyAd
        {
            get
            {
                return ResourceManager.GetString("SoyAd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to İstatistikler Genel Bakış.
        /// </summary>
        public static string staticover
        {
            get
            {
                return ResourceManager.GetString("staticover", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon
        {
            get
            {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TÜM FİLMLER.
        /// </summary>
        public static string TümHaberler
        {
            get
            {
                return ResourceManager.GetString("TümHaberler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Türler.
        /// </summary>
        public static string Türler
        {
            get
            {
                return ResourceManager.GetString("Türler", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ülke.
        /// </summary>
        public static string Ülke
        {
            get
            {
                return ResourceManager.GetString("Ülke", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Kullanıcı Sayısı.
        /// </summary>
        public static string UserCount
        {
            get
            {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YAYINLANMA TARİHİ.
        /// </summary>
        public static string YayınlanmaTarihi
        {
            get
            {
                return ResourceManager.GetString("YayınlanmaTarihi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeni Oluştur.
        /// </summary>
        public static string YeniOluştur
        {
            get
            {
                return ResourceManager.GetString("YeniOluştur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YÖNETİM PANELİ.
        /// </summary>
        public static string YönetimPaneli
        {
            get
            {
                return ResourceManager.GetString("YönetimPaneli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yönetmen İşlemleri.
        /// </summary>
        //public static string Yönetmenİşlemleri
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("Yönetmenİşlemleri", resourceCulture);
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to Yönetmenler.
        /// </summary>
        //public static string Yönetmenler
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("Yönetmenler", resourceCulture);
        //    }
        //}
    }
}
